### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bhj128128** [mrgeneralgoo/typecho-update-assistant#1]
插件无法使用。禁用删除插件后，在控制台那仍然有一行update blogging platform

**Comment by mrgeneralgoo** [comment]
Sorry , I forgot to handle the deactivate action.

[Already fixed](https://github.com/mrgeneralgoo/typecho-update-assistant/commit/3dc8025b0f4dfaf01e6cb3945e8cb19edb3eefa5#diff-cea02a77483ae0806e5b6ac3f52f15dcR26).
